// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: rpc/paxos-messages.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmallestUndecidedIndex uint64 `protobuf:"varint,1,opt,name=smallestUndecidedIndex,proto3" json:"smallestUndecidedIndex,omitempty"`
	ProposalNumber         uint64 `protobuf:"varint,2,opt,name=proposalNumber,proto3" json:"proposalNumber,omitempty"`
}

func (x *PrepareBody) Reset() {
	*x = PrepareBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBody) ProtoMessage() {}

func (x *PrepareBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBody.ProtoReflect.Descriptor instead.
func (*PrepareBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareBody) GetSmallestUndecidedIndex() uint64 {
	if x != nil {
		return x.SmallestUndecidedIndex
	}
	return 0
}

func (x *PrepareBody) GetProposalNumber() uint64 {
	if x != nil {
		return x.ProposalNumber
	}
	return 0
}

type PromiseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decrees                map[uint64]string `protobuf:"bytes,1,rep,name=decrees,proto3" json:"decrees,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CorrespondingBallotNum map[uint64]uint64 `protobuf:"bytes,2,rep,name=correspondingBallotNum,proto3" json:"correspondingBallotNum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AckedAsLeader          bool              `protobuf:"varint,3,opt,name=ackedAsLeader,proto3" json:"ackedAsLeader,omitempty"`
}

func (x *PromiseBody) Reset() {
	*x = PromiseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromiseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseBody) ProtoMessage() {}

func (x *PromiseBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseBody.ProtoReflect.Descriptor instead.
func (*PromiseBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PromiseBody) GetDecrees() map[uint64]string {
	if x != nil {
		return x.Decrees
	}
	return nil
}

func (x *PromiseBody) GetCorrespondingBallotNum() map[uint64]uint64 {
	if x != nil {
		return x.CorrespondingBallotNum
	}
	return nil
}

func (x *PromiseBody) GetAckedAsLeader() bool {
	if x != nil {
		return x.AckedAsLeader
	}
	return false
}

type AcceptBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BallotNumber uint64 `protobuf:"varint,1,opt,name=ballotNumber,proto3" json:"ballotNumber,omitempty"`
	Decree       string `protobuf:"bytes,2,opt,name=decree,proto3" json:"decree,omitempty"`
	LogIndex     uint64 `protobuf:"varint,3,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
}

func (x *AcceptBody) Reset() {
	*x = AcceptBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptBody) ProtoMessage() {}

func (x *AcceptBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptBody.ProtoReflect.Descriptor instead.
func (*AcceptBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptBody) GetBallotNumber() uint64 {
	if x != nil {
		return x.BallotNumber
	}
	return 0
}

func (x *AcceptBody) GetDecree() string {
	if x != nil {
		return x.Decree
	}
	return ""
}

func (x *AcceptBody) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

type AcceptedBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AcceptedBody) Reset() {
	*x = AcceptedBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptedBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedBody) ProtoMessage() {}

func (x *AcceptedBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedBody.ProtoReflect.Descriptor instead.
func (*AcceptedBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptedBody) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AcceptedBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decree string `protobuf:"bytes,1,opt,name=decree,proto3" json:"decree,omitempty"`
}

func (x *CommandBody) Reset() {
	*x = CommandBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandBody) ProtoMessage() {}

func (x *CommandBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandBody.ProtoReflect.Descriptor instead.
func (*CommandBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CommandBody) GetDecree() string {
	if x != nil {
		return x.Decree
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Committed    bool   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LearnBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decree   string `protobuf:"bytes,1,opt,name=decree,proto3" json:"decree,omitempty"`
	LogIndex uint64 `protobuf:"varint,2,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
}

func (x *LearnBody) Reset() {
	*x = LearnBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnBody) ProtoMessage() {}

func (x *LearnBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnBody.ProtoReflect.Descriptor instead.
func (*LearnBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{6}
}

func (x *LearnBody) GetDecree() string {
	if x != nil {
		return x.Decree
	}
	return ""
}

func (x *LearnBody) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

type LearnAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acked bool `protobuf:"varint,1,opt,name=acked,proto3" json:"acked,omitempty"`
}

func (x *LearnAck) Reset() {
	*x = LearnAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnAck) ProtoMessage() {}

func (x *LearnAck) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnAck.ProtoReflect.Descriptor instead.
func (*LearnAck) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{7}
}

func (x *LearnAck) GetAcked() bool {
	if x != nil {
		return x.Acked
	}
	return false
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Log) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetLogBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLogBody) Reset() {
	*x = GetLogBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogBody) ProtoMessage() {}

func (x *GetLogBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogBody.ProtoReflect.Descriptor instead.
func (*GetLogBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{9}
}

type HeartbeatBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicaNum uint32 `protobuf:"varint,1,opt,name=replicaNum,proto3" json:"replicaNum,omitempty"`
}

func (x *HeartbeatBody) Reset() {
	*x = HeartbeatBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatBody) ProtoMessage() {}

func (x *HeartbeatBody) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatBody.ProtoReflect.Descriptor instead.
func (*HeartbeatBody) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatBody) GetReplicaNum() uint32 {
	if x != nil {
		return x.ReplicaNum
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_paxos_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_paxos_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_rpc_paxos_messages_proto_rawDescGZIP(), []int{11}
}

var File_rpc_paxos_messages_proto protoreflect.FileDescriptor

var file_rpc_paxos_messages_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2d, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x0b, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x36, 0x0a, 0x16, 0x73, 0x6d, 0x61,
	0x6c, 0x6c, 0x65, 0x73, 0x74, 0x55, 0x6e, 0x64, 0x65, 0x63, 0x69, 0x64, 0x65, 0x64, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x73, 0x6d, 0x61, 0x6c, 0x6c,
	0x65, 0x73, 0x74, 0x55, 0x6e, 0x64, 0x65, 0x63, 0x69, 0x64, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xd1, 0x02, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x6d, 0x69, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x64, 0x65, 0x63,
	0x72, 0x65, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x72, 0x6f,
	0x6d, 0x69, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x65, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x64, 0x65, 0x63, 0x72, 0x65, 0x65, 0x73, 0x12, 0x60,
	0x0a, 0x16, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42,
	0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x2e, 0x43, 0x6f, 0x72,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74,
	0x4e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x16, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d,
	0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x73, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x73,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x3a, 0x0a, 0x0c, 0x44, 0x65, 0x63, 0x72, 0x65, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x49, 0x0a, 0x1b, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x64, 0x0a,
	0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x62,
	0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x63, 0x72, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x22, 0x44, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x72,
	0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x72, 0x65, 0x65,
	0x22, 0x53, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x09, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x72, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x72, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f,
	0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x20, 0x0a, 0x08, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x41,
	0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x22, 0x1f, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x2f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x4e, 0x75, 0x6d, 0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x32, 0xee, 0x01, 0x0a, 0x05, 0x50, 0x61, 0x78,
	0x6f, 0x73, 0x12, 0x2f, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x0c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42, 0x6f, 0x64,
	0x79, 0x1a, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x0c,
	0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x0c, 0x2e, 0x50,
	0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x12, 0x0b, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x42, 0x6f, 0x64,
	0x79, 0x1a, 0x0d, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x1e, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x12, 0x0a, 0x2e, 0x4c, 0x65, 0x61, 0x72,
	0x6e, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x09, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x41, 0x63, 0x6b,
	0x12, 0x1b, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x0b, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x04, 0x2e, 0x4c, 0x6f, 0x67, 0x12, 0x2a, 0x0a,
	0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x0e, 0x2e, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x0d, 0x2e, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x77, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x31,
	0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_paxos_messages_proto_rawDescOnce sync.Once
	file_rpc_paxos_messages_proto_rawDescData = file_rpc_paxos_messages_proto_rawDesc
)

func file_rpc_paxos_messages_proto_rawDescGZIP() []byte {
	file_rpc_paxos_messages_proto_rawDescOnce.Do(func() {
		file_rpc_paxos_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_paxos_messages_proto_rawDescData)
	})
	return file_rpc_paxos_messages_proto_rawDescData
}

var file_rpc_paxos_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_paxos_messages_proto_goTypes = []interface{}{
	(*PrepareBody)(nil),     // 0: PrepareBody
	(*PromiseBody)(nil),     // 1: PromiseBody
	(*AcceptBody)(nil),      // 2: AcceptBody
	(*AcceptedBody)(nil),    // 3: AcceptedBody
	(*CommandBody)(nil),     // 4: CommandBody
	(*CommandResponse)(nil), // 5: CommandResponse
	(*LearnBody)(nil),       // 6: LearnBody
	(*LearnAck)(nil),        // 7: LearnAck
	(*Log)(nil),             // 8: Log
	(*GetLogBody)(nil),      // 9: GetLogBody
	(*HeartbeatBody)(nil),   // 10: HeartbeatBody
	(*HeartbeatAck)(nil),    // 11: HeartbeatAck
	nil,                     // 12: PromiseBody.DecreesEntry
	nil,                     // 13: PromiseBody.CorrespondingBallotNumEntry
}
var file_rpc_paxos_messages_proto_depIdxs = []int32{
	12, // 0: PromiseBody.decrees:type_name -> PromiseBody.DecreesEntry
	13, // 1: PromiseBody.correspondingBallotNum:type_name -> PromiseBody.CorrespondingBallotNumEntry
	4,  // 2: Paxos.ClientCommand:input_type -> CommandBody
	0,  // 3: Paxos.Prepare:input_type -> PrepareBody
	2,  // 4: Paxos.Accept:input_type -> AcceptBody
	6,  // 5: Paxos.Learn:input_type -> LearnBody
	9,  // 6: Paxos.GetLog:input_type -> GetLogBody
	10, // 7: Paxos.Heartbeat:input_type -> HeartbeatBody
	5,  // 8: Paxos.ClientCommand:output_type -> CommandResponse
	1,  // 9: Paxos.Prepare:output_type -> PromiseBody
	3,  // 10: Paxos.Accept:output_type -> AcceptedBody
	7,  // 11: Paxos.Learn:output_type -> LearnAck
	8,  // 12: Paxos.GetLog:output_type -> Log
	11, // 13: Paxos.Heartbeat:output_type -> HeartbeatAck
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_paxos_messages_proto_init() }
func file_rpc_paxos_messages_proto_init() {
	if File_rpc_paxos_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_paxos_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromiseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptedBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearnBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearnAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_paxos_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_paxos_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_paxos_messages_proto_goTypes,
		DependencyIndexes: file_rpc_paxos_messages_proto_depIdxs,
		MessageInfos:      file_rpc_paxos_messages_proto_msgTypes,
	}.Build()
	File_rpc_paxos_messages_proto = out.File
	file_rpc_paxos_messages_proto_rawDesc = nil
	file_rpc_paxos_messages_proto_goTypes = nil
	file_rpc_paxos_messages_proto_depIdxs = nil
}
